### ISSUE TITLE
Error: Cannot read property 'launch' of null at PlatformSender.launch

### ISSUE THREAD

**Issue by manne01** [angelnu/castv2-player#2]
Has anybody some idea where this error might come from? It appears only if I try to play a url with a group of chromecast speakers...

**Comment by angelnu** [comment]
Sometimes the player loose connection with the Chromecast and then has to reconnect. This might explain the above.

Do you have the full log of the problem?

**Comment by manne01** [comment]
All I have is:
`chromecast.0 2017-07-07 12:11:56.065 error GanzeWohnung - Cannot play file "http://mp3-live.dasding.de/dasding_m.m3u": TypeError: Cannot read property 'launch' of null
chromecast.0 2017-07-07 12:11:56.065 error at process._tickCallback (node.js:385:9)
chromecast.0 2017-07-07 12:11:56.065 error at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:66:45
chromecast.0 2017-07-07 12:11:56.065 error at PersistentClient._launchPromise (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:303:14)
chromecast.0 2017-07-07 12:11:56.065 error at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:304:16
chromecast.0 2017-07-07 12:11:56.065 error at PlatformSender.launch (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/node_modules/castv2-client/lib/senders/platform.js:94:16)
chromecast.0 2017-07-07 12:11:56.065 error GanzeWohnung - Error playing playlist - TypeError: Cannot read property 'launch' of null`

**Comment by angelnu** [comment]
Uhm, I tried playing the link you use in iobroker with my "allHouse" group and it worked so let us see what is different in your setup.

- What version are you using? Latest version from iobroker.chromecast is 1.3.2
- Does it always fail or it failed only once?
- Does it work with individual chromecast devices?

**Comment by manne01** [comment]
Yes, I am on version 1.3.2 already. I did not find out when exactly it happens. What I can say is: After a restart of the adapter, everything is fine again for a while. I can not actively reproduce it but at least after 24h it occurs again. It seems quite interessting to me what you say about lost connections. I assume the adapter looses some connection - but - when this error happens, I can play URLs with no problem to any single CC device. The only thing producing the error is trying to play on my only group.

What I will do next is if it happens I try some other player (mobile app or so) and try to play something to the group. And see if this changes something...

**Comment by angelnu** [comment]
Something else I observe is that once I play in a member of the group is that the connection closes. I "think" that Chromecast destroys the group when one device is used individually and re-creates it later.

**Comment by manne01** [comment]
Happened today again. Tried to play a url on my speaker-group, error. 
I could play a song with some mobile app without any problem. Doing that, the group played perfectly. In iobroker the volume control of the group was not "connected" to the single player ones. 
After adapter restart anything fine and volume controls connected.

How can I help to debug this?
How can I fetch a detailed connection status when it happens?

**Comment by manne01** [comment]
Today the adapter has even terminated.

`host.meinhost	2017-07-25 18:53:33.524	info	Restart adapter system.adapter.chromecast.0 because enabled
host.meinhost	2017-07-25 18:53:33.523	error	instance system.adapter.chromecast.0 terminated with code 0 (OK)
chromecast.0	2017-07-25 18:53:33.327	error	GanzeWohnung - Cannot play file "http://mp3ad.egofm.c.nmdn.net/ps-egofm_192/livestream.mp3": TypeError: Cannot read property 'launch' of null
chromecast.0	2017-07-25 18:53:33.327	error	GanzeWohnung - Error playing playlist - TypeError: Cannot read property 'launch' of null at PlatformSender.launch (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/node_mo
chromecast.0	2017-07-25 18:53:33.327	info	GanzeWohnung - Try to launch default player
chromecast.0	2017-07-25 18:53:33.327	info	GanzeWohnung - Try to play url - http://mp3ad.egofm.c.nmdn.net/ps-egofm_192/livestream.mp3
chromecast.0	2017-07-25 18:53:33.279	debug	GanzeWohnung - device stateChange chromecast.0.GanzeWohnung.status.playing {"val":true,"ack":false,"ts":1501001613268,"q":0,"from":"system.adapter.javascript.0","lc":1501001613268}
chromecast.0	2017-07-25 18:53:33.272	debug	inMem message chromecast.0.* chromecast.0.GanzeWohnung.status.playing
`

**Comment by manne01** [comment]
Is there something I can do to support and get closer to the reason?

**Comment by angelnu** [comment]
@manne01 - are you still seeing this problem? The updated chromecast firmware removed some of the errors I had been seeing before so maybe the problem is gone for you as well.
